export const quotes = [
  { "text": "Você não se eleva ao nível de seus objetivos, você cai ao nível de seus sistemas.", "author": "James Clear" },
  { "text": "Pequenos hábitos fazem uma grande diferença.", "author": "James Clear" },
  { "text": "A verdadeira mudança de comportamento é mudança de identidade.", "author": "James Clear" },
  { "text": "O sucesso é a soma de pequenos esforços repetidos diariamente.", "author": "Robert Collier" },
  { "text": "Nós somos aquilo que fazemos repetidamente. Excelência, então, não é um ato, mas um hábito.", "author": "Aristóteles" },
  { "text": "A disciplina é a ponte entre metas e realizações.", "author": "Jim Rohn" },
  { "text": "Ou você controla o seu dia, ou o seu dia controla você.", "author": "Jim Rohn" },
  { "text": "Motivação é o que te faz começar. Hábito é o que te mantém.", "author": "Jim Rohn" },
  { "text": "A dor da disciplina pesa gramas; a dor do arrependimento pesa toneladas.", "author": "Jim Rohn" },
  { "text": "Não é sobre ter tempo, é sobre fazer tempo.", "author": "Autor desconhecido" },

  { "text": "A ação é a chave fundamental para todo sucesso.", "author": "Pablo Picasso" },
  { "text": "Comece onde você está. Use o que você tem. Faça o que você pode.", "author": "Arthur Ashe" },
  { "text": "Feito é melhor que perfeito.", "author": "Sheryl Sandberg" },
  { "text": "Não espere por oportunidade. Crie-a.", "author": "George Bernard Shaw" },
  { "text": "A melhor maneira de prever o futuro é criá-lo.", "author": "Peter Drucker" },
  { "text": "Você perde 100% das chances que não aproveita.", "author": "Wayne Gretzky" },
  { "text": "A persistência realiza o impossível.", "author": "Provérbio chinês" },
  { "text": "Grandes coisas são feitas por uma série de pequenas coisas reunidas.", "author": "Vincent van Gogh" },
  { "text": "O sucesso geralmente vem para aqueles que estão ocupados demais para procurar por ele.", "author": "Henry David Thoreau" },
  { "text": "Não conte os dias, faça os dias contarem.", "author": "Muhammad Ali" },

  { "text": "A coragem não é a ausência do medo, mas a decisão de que algo é mais importante que o medo.", "author": "Ambrose Redmoon" },
  { "text": "Se você quer algo que nunca teve, precisa fazer algo que nunca fez.", "author": "Thomas Jefferson" },
  { "text": "A disciplina é escolher entre o que você quer agora e o que você quer mais.", "author": "Abraham Lincoln (atribuído)" },
  { "text": "O sucesso não é final, o fracasso não é fatal: é a coragem de continuar que conta.", "author": "Winston Churchill" },
  { "text": "A energia e a persistência conquistam todas as coisas.", "author": "Benjamin Franklin" },
  { "text": "Você se torna aquilo em que pensa na maior parte do tempo.", "author": "Earl Nightingale" },
  { "text": "A única limitação é aquela que você aceita.", "author": "Napoleon Hill" },
  { "text": "Tudo o que a mente pode conceber e acreditar, ela pode conquistar.", "author": "Napoleon Hill" },
  { "text": "A vitória pertence ao mais perseverante.", "author": "Napoleon Bonaparte" },
  { "text": "A oportunidade está perdida para aqueles que a deixam passar.", "author": "Thomas Edison" },

  { "text": "A maneira de começar é parar de falar e começar a fazer.", "author": "Walt Disney" },
  { "text": "Se você pode sonhar, você pode fazer.", "author": "Walt Disney" },
  { "text": "O único lugar onde o sucesso vem antes do trabalho é no dicionário.", "author": "Vidal Sassoon" },
  { "text": "Não é o que você faz de vez em quando que importa, é o que você faz consistentemente.", "author": "Tony Robbins" },
  { "text": "A decisão é o ponto inicial de toda realização.", "author": "Tony Robbins" },
  { "text": "Defina suas metas altas e não pare até alcançá-las.", "author": "Bo Jackson" },
  { "text": "Se você quer ser bem-sucedido, precisa aceitar o desconforto.", "author": "Autor desconhecido" },
  { "text": "A excelência não é um ato, é um hábito.", "author": "Aristóteles" },
  { "text": "A vida começa onde sua zona de conforto termina.", "author": "Neale Donald Walsch" },
  { "text": "Você nunca falha até parar de tentar.", "author": "Albert Einstein" },

  { "text": "A diferença entre o impossível e o possível está na determinação.", "author": "Tommy Lasorda" },
  { "text": "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.", "author": "Winston Churchill" },
  { "text": "Não espere. O tempo nunca será o certo.", "author": "Napoleon Hill" },
  { "text": "A disciplina é a mãe do sucesso.", "author": "Ésquilo" },
  { "text": "Seja mais forte que suas desculpas.", "author": "Autor desconhecido" },
  { "text": "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.", "author": "Zig Ziglar" },
  { "text": "As pessoas bem-sucedidas fazem o que as pessoas sem sucesso não estão dispostas a fazer.", "author": "Jim Rohn" },
  { "text": "A repetição é a mãe da habilidade.", "author": "Tony Robbins" },
  { "text": "Se você quer mudar sua vida, mude algo que você faz todos os dias.", "author": "John C. Maxwell" },
  { "text": "O preço da excelência é a disciplina.", "author": "William Arthur Ward" }
];